lang: sv-SE
title: Obround på Svenska
tagline: Vad är en Rektirkel?
description: Obround är en geometrisk figur, men namnet är från Engelskan. Vad heter Obround på Svenska? Och vad är en Obround egentligen?
