description: Obround är en geometrisk figur, men namnet är från Engelskan.
  Vad heter Obround på Svenska?
  Och vad är en Obround egentligen?
lang: sv-SE
tagline: Vad är en Rektirkel?
title: Obround på Svenska
